'use strict';
module.exports = function(Test) {
  Test.disableRemoteMethodByName('patchOrCreate', true);
  Test.disableRemoteMethodByName('patchOrCreateWithWhere', true);
  Test.disableRemoteMethodByName('upsert', true);
  Test.disableRemoteMethodByName('upsertWithWhere', true);
  Test.disableRemoteMethodByName('patch', true);
  Test.disableRemoteMethodByName('create', true);
  Test.disableRemoteMethodByName('replace', true);
  Test.disableRemoteMethodByName('replaceById', true);
  Test.disableRemoteMethodByName('replaceOrCreate', true);
  Test.disableRemoteMethodByName('exists', true);
  Test.disableRemoteMethodByName('count', true);
  Test.disableRemoteMethodByName('find', true);
  Test.disableRemoteMethodByName('findById', true);
  Test.disableRemoteMethodByName('findOne', true);
  Test.disableRemoteMethodByName('findOrCreate', true);
  Test.disableRemoteMethodByName('destroyById', true);
  Test.disableRemoteMethodByName('destroyAll', true);
  Test.disableRemoteMethodByName('remove', true);
  Test.disableRemoteMethodByName('removeById', true);
  Test.disableRemoteMethodByName('deleteAll', true);
  Test.disableRemoteMethodByName('deleteById', true);
  Test.disableRemoteMethodByName('updateAll', true);
  Test.disableRemoteMethodByName('updateOrCreate', true);
  Test.disableRemoteMethodByName('createChangeStream', true);
  Test.disableRemoteMethodByName('updateLastChange', true);
  Test.disableRemoteMethodByName('createUpdates', true);
  console.log();
};
